version: '3.7'
services:
  jupyter:
    image: jupyter/minimal-notebook
    privileged: true
    user: root
    ports:
      - 8888:8888
      - 50001:50001
    container_name: jupyter
    volumes:
      - ~/jupyter:/var/jupyter_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
